// <auto-generated />
using System;
using FanShop.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FanShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250820160455_AddTask")]
    partial class AddTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("FanShop.Models.DayTask", b =>
                {
                    b.Property<int>("DayTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskCategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DayTaskID");

                    b.HasIndex("TaskCategoryID");

                    b.ToTable("DayTasks");
                });

            modelBuilder.Entity("FanShop.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FanShop.Models.TaskCategory", b =>
                {
                    b.Property<int>("TaskCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TaskCategoryID");

                    b.ToTable("TaskCategories");
                });

            modelBuilder.Entity("FanShop.Models.WorkDay", b =>
                {
                    b.Property<int>("WorkDayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkDayID");

                    b.ToTable("WorkDays");
                });

            modelBuilder.Entity("FanShop.Models.WorkDayEmployee", b =>
                {
                    b.Property<int>("WorkDayEmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkDayID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkDuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkDayEmployeeID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("WorkDayID");

                    b.ToTable("WorkDayEmployee");
                });

            modelBuilder.Entity("FanShop.Models.DayTask", b =>
                {
                    b.HasOne("FanShop.Models.TaskCategory", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskCategoryID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FanShop.Models.WorkDayEmployee", b =>
                {
                    b.HasOne("FanShop.Models.Employee", "Employee")
                        .WithMany("WorkDayEmployees")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FanShop.Models.WorkDay", "WorkDay")
                        .WithMany("WorkDayEmployees")
                        .HasForeignKey("WorkDayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("WorkDay");
                });

            modelBuilder.Entity("FanShop.Models.Employee", b =>
                {
                    b.Navigation("WorkDayEmployees");
                });

            modelBuilder.Entity("FanShop.Models.TaskCategory", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("FanShop.Models.WorkDay", b =>
                {
                    b.Navigation("WorkDayEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
