// <auto-generated />
using System;
using FanShop.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FanShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721083755_AddShopPositionSalaryHistory")]
    partial class AddShopPositionSalaryHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("FanShop.Models.DayTask", b =>
                {
                    b.Property<int>("DayTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndHour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartHour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaskCategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DayTaskID");

                    b.HasIndex("TaskCategoryID");

                    b.ToTable("DayTasks");
                });

            modelBuilder.Entity("FanShop.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FanShop.Models.Position", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShopID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PositionID");

                    b.HasIndex("ShopID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("FanShop.Models.SalaryHistory", b =>
                {
                    b.Property<int>("SalaryHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SalaryHistoryID");

                    b.HasIndex("PositionID");

                    b.ToTable("SalaryHistories");
                });

            modelBuilder.Entity("FanShop.Models.Shop", b =>
                {
                    b.Property<int>("ShopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ShopID");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("FanShop.Models.TaskCategory", b =>
                {
                    b.Property<int>("TaskCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTask")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TaskCategoryID");

                    b.ToTable("TaskCategories");
                });

            modelBuilder.Entity("FanShop.Models.WorkDay", b =>
                {
                    b.Property<int>("WorkDayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkDayID");

                    b.ToTable("WorkDays");
                });

            modelBuilder.Entity("FanShop.Models.WorkDayEmployee", b =>
                {
                    b.Property<int>("WorkDayEmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeInPass")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeInSalary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SalaryAtMoment")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkDayID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkDuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkDayEmployeeID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PositionID");

                    b.HasIndex("WorkDayID");

                    b.ToTable("WorkDayEmployee");
                });

            modelBuilder.Entity("FanShop.Models.DayTask", b =>
                {
                    b.HasOne("FanShop.Models.TaskCategory", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskCategoryID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FanShop.Models.Position", b =>
                {
                    b.HasOne("FanShop.Models.Shop", "Shop")
                        .WithMany("Positions")
                        .HasForeignKey("ShopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("FanShop.Models.SalaryHistory", b =>
                {
                    b.HasOne("FanShop.Models.Position", "Position")
                        .WithMany("SalaryHistories")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("FanShop.Models.WorkDayEmployee", b =>
                {
                    b.HasOne("FanShop.Models.Employee", "Employee")
                        .WithMany("WorkDayEmployee")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FanShop.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FanShop.Models.WorkDay", "WorkDay")
                        .WithMany("WorkDayEmployee")
                        .HasForeignKey("WorkDayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Position");

                    b.Navigation("WorkDay");
                });

            modelBuilder.Entity("FanShop.Models.Employee", b =>
                {
                    b.Navigation("WorkDayEmployee");
                });

            modelBuilder.Entity("FanShop.Models.Position", b =>
                {
                    b.Navigation("SalaryHistories");
                });

            modelBuilder.Entity("FanShop.Models.Shop", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("FanShop.Models.TaskCategory", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("FanShop.Models.WorkDay", b =>
                {
                    b.Navigation("WorkDayEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
